function(aurora_xxhash_apply_patches xxhash_source_dir)
  if (NOT IS_ABSOLUTE "${xxhash_source_dir}")
    message(FATAL_ERROR "aurora: xxHash source path must be absolute")
  endif ()
  set(_file "${xxhash_source_dir}/cmake_unofficial/CMakeLists.txt")
  if (NOT EXISTS "${_file}")
    message(FATAL_ERROR "aurora: xxHash source tree has no cmake_unofficial/CMakeLists.txt")
  endif ()
  set(_old [=[CMAKE_HOST_SYSTEM_INFORMATION(RESULT PLATFORM QUERY OS_PLATFORM)]=])
  set(_new [=[set(PLATFORM "${CMAKE_SYSTEM_PROCESSOR}")]=])
  set(_old_regex [=[CMAKE_HOST_SYSTEM_INFORMATION\(RESULT PLATFORM QUERY OS_PLATFORM\)]=])
  set(_new_regex [=[set\(PLATFORM "\$\{CMAKE_SYSTEM_PROCESSOR\}"\)]=])
  file(READ "${_file}" _content)
  string(REGEX MATCHALL "${_old_regex}" _old_matches "${_content}")
  string(REGEX MATCHALL "${_new_regex}" _new_matches "${_content}")
  list(LENGTH _old_matches _old_count)
  list(LENGTH _new_matches _new_count)
  if (_old_count EQUAL 0 AND _new_count EQUAL 1)
    return()
  endif ()
  if (NOT _old_count EQUAL 1 OR NOT _new_count EQUAL 0)
    message(FATAL_ERROR "aurora: xxHash host-platform patch does not match the pinned source")
  endif ()
  string(REPLACE "${_old}" "${_new}" _content "${_content}")
  file(WRITE "${_file}" "${_content}")
  message(STATUS "aurora: xxHash host-platform patch applied")
endfunction()

if (CMAKE_SCRIPT_MODE_FILE AND DEFINED XXHASH_SOURCE_DIR)
  aurora_xxhash_apply_patches("${XXHASH_SOURCE_DIR}")
endif ()
